#!/bin/sh
PROCESSES=`ps -e|grep "\.hpacucli" |grep -v grep`
if [ "$PROCESSES" != "" ]; then
        echo "Another instance of hpacucli is running! Stop it first."
        exit 1;
fi
 
HPACUCLI_BIN_INSTALLATION_DIR=/usr/local/agenttools/agent/hp/
export LD_LIBRARY_PATH=$HPACUCLI_BIN_INSTALLATION_DIR
${HPACUCLI_BIN_INSTALLATION_DIR}mklocks.sh hpacucli
if [ `uname -m` = "ia64" ]; then
/usr/bin/prctl --unaligned=silent $HPACUCLI_BIN_INSTALLATION_DIR.hpacucli $*
else
$HPACUCLI_BIN_INSTALLATION_DIR.hpacucli $*
fi
